spring:
  application:
    name: GT

  security:
    user:
      name: breno
      password: 159753

  datasource:
    url: jdbc:h2:mem:GTDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML

  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
